#!/usr/bin/env bash
# deploy/load-secrets.sh
# ─────────────────────────────────────────────────────────────────────────────
# Fetches secrets from AWS SSM Parameter Store (or Secrets Manager) using the
# EC2 instance IAM role and writes them to /opt/triage/.env before compose up.
#
# Prerequisites:
#   - EC2 instance IAM role must have:
#       ssm:GetParameter
#       ssm:GetParameters
#       secretsmanager:GetSecretValue  (if using Secrets Manager)
#   - aws-cli v2 installed: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html
#   - Set TRIAGE_SSM_PATH below to your SSM path prefix
#
# USAGE:
#   sudo bash /opt/triage/deploy/load-secrets.sh
#   sudo systemctl restart triage-compose
#
# SSM Parameters expected (SecureString type):
#   /triage/HF_TOKEN          → Hugging Face API token
#   /triage/DEFAULT_TASK      → (optional) task1_esi_assignment etc.
#
# ─────────────────────────────────────────────────────────────────────────────
set -euo pipefail

TRIAGE_SSM_PATH="/triage"
TRIAGE_ENV_FILE="/opt/triage/.env"
AWS_REGION="${AWS_REGION:-us-east-1}"

log() { echo "[load-secrets] $*"; }
err() { echo "[load-secrets] ERROR: $*" >&2; exit 1; }

command -v aws >/dev/null 2>&1 || err "aws-cli not found. Install: https://docs.aws.amazon.com/cli/latest/userguide/getting-started-install.html"

log "Fetching secrets from SSM path: ${TRIAGE_SSM_PATH} (region: ${AWS_REGION})"

# ── Helper: get a single SSM parameter (returns empty string if missing) ─────
get_ssm() {
    local name="$1"
    aws ssm get-parameter \
        --name "${TRIAGE_SSM_PATH}/${name}" \
        --with-decryption \
        --query "Parameter.Value" \
        --output text \
        --region "${AWS_REGION}" 2>/dev/null || echo ""
}

HF_TOKEN="$(get_ssm HF_TOKEN)"
DEFAULT_TASK="$(get_ssm DEFAULT_TASK)"

# ── Write .env ────────────────────────────────────────────────────────────────
cat > "${TRIAGE_ENV_FILE}" <<EOF
# Auto-generated by deploy/load-secrets.sh — do not edit manually
# Generated: $(date -Iseconds)
HF_TOKEN=${HF_TOKEN}
DEFAULT_TASK=${DEFAULT_TASK:-task1_esi_assignment}
AWS_REGION=${AWS_REGION}
EOF

chmod 600 "${TRIAGE_ENV_FILE}"
log "Written to ${TRIAGE_ENV_FILE} (permissions: 600)"

# ── Optional: also pull from Secrets Manager (uncomment if preferred) ─────────
# SECRET_JSON=$(aws secretsmanager get-secret-value \
#     --secret-id triage/production \
#     --query SecretString --output text --region "${AWS_REGION}")
# HF_TOKEN=$(echo "$SECRET_JSON" | python3 -c "import sys,json; print(json.load(sys.stdin).get('HF_TOKEN',''))")

log "Done. Run: docker compose up -d --build"
